mainHome:
    uri: /
    controller: App\Controller\MainController
    method: home

mainAbout:
    uri: /a-propos
    controller: App\Controller\MainController
    method: about

beerList:
    uri: /bieres
    controller: App\Controller\BeerController
    method: list

beerSingle:
    uri: /biere
    controller: App\Controller\BeerController
    method: single

userRegister:
    uri: /inscription
    controller: App\Controller\UserController
    method: register

userLogin:
    uri: /connexion
    controller: App\Controller\UserController
    method: login
