# Main
mainHome:
    uri: /
    controller: App\Controller\MainController
    method: home

mainAbout:
    uri: /a-propos
    controller: App\Controller\MainController
    method: about

# Beer
beerList:
    uri: /bieres
    controller: App\Controller\BeerController
    method: list

beerSingle:
    uri: /biere
    controller: App\Controller\BeerController
    method: single

beerToggleFavorite:
    uri: /biere/favori
    controller: App\Controller\BeerController
    method: toggleFavorite

# User
userRegister:
    uri: /inscription
    controller: App\Controller\UserController
    method: register

userLogin:
    uri: /connexion
    controller: App\Controller\UserController
    method: login

userLogout:
    uri: /deconnexion
    controller: App\Controller\UserController
    method: logout
